version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123!
      POSTGRES_DB: dellin_dictionary
    ports:
      - "6432:5432"
    volumes:
      - pg-data:/var/lib/postgresql18/data

volumes:
  pg-data:
